In [5]:
from LEN_Scorer import Scorer
import pandas as pd
import numpy as np
from sklearn.preprocessing import KBinsDiscretizer, OneHotEncoder

In [6]:
mimicDF = pd.read_csv('../LEN_Test/data/StaticData.csv')
targetDF = mimicDF[['deathperiod']]
mimicDF = mimicDF.drop(columns=['PatientID', 'deathperiod'])

In [3]:
for col in mimicDF:
    mimicDF[col] = mimicDF[col].fillna(mimicDF[col].mode()[0])

In [4]:
mimicDF

,los,gender,age,comorbidity,sofa,respiration,coagulation,liver,renal,cardiovascular,cns
0,9,1,74.19,7,7,0.0,1.0,0.0,0.0,3.0,3.0
1,2,0,75.00,4,2,3.0,0.0,0.0,1.0,3.0,1.0
2,16,0,51.92,4,2,3.0,0.0,0.0,0.0,3.0,2.0
3,12,0,51.73,-13,4,2.0,2.0,0.0,0.0,3.0,0.0
4,7,0,62.07,0,3,0.0,2.0,0.0,1.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
5257,120,1,36.61,5,10,3.0,3.0,4.0,0.0,3.0,0.0
5258,13,0,53.90,12,4,3.0,0.0,0.0,0.0,3.0,1.0
5259,4,0,58.93,18,5,3.0,1.0,0.0,4.0,3.0,0.0
5260,16,0,68.98,-4,3,1.0,2.0,0.0,0.0,3.0,0.0
5261,2,1,26.15,-4,2,0.0,0.0,0.0,0.0,3.0,2.0

In [8]:
dataNeedingEncodingDF = mimicDF[['los', 'age', 'comorbidity', 'sofa']]

In [9]:
bins = 5

est = KBinsDiscretizer(n_bins=bins, encode='ordinal', strategy='kmeans')
categorisedDF = pd.DataFrame(data=est.fit_transform(dataNeedingEncodingDF), columns=dataNeedingEncodingDF.columns)

In [10]:
categorisedDF

      los  age  comorbidity  sofa
0     0.0  2.0          1.0   1.0
1     0.0  2.0          1.0   0.0
2     1.0  1.0          1.0   0.0
3     0.0  1.0          0.0   0.0
4     0.0  1.0          0.0   0.0
...   ...  ...          ...   ...
5257  3.0  0.0          1.0   2.0
5258  0.0  1.0          2.0   0.0
5259  0.0  1.0          2.0   0.0
5260  1.0  2.0          0.0   0.0
5261  0.0  0.0          0.0   0.0

[5262 rows x 4 columns]